### ISSUE TITLE
authorizedCallback Validation, iat rejected id_token was issued too far away from the current time

### ISSUE THREAD

**Issue by Brocy** [admin-ch/CovidCode-UI#11]
We are facing this issue, in our installation.

`angular-auth-oidc-client.js:393 authorizedCallback Validation, iat rejected id_token was issued too far away from the current time`

Searching on google we find that is a bug in auth client 
https://github.com/damienbod/angular-auth-oidc-client/issues/175

Fix on version v11
https://github.com/damienbod/angular-auth-oidc-client/releases

> Id_Token is rejected because of timing issue when server hour is different then client hour
> fix validate, fix max time offset #175

Anyone facing the same issue? possible workaround ?
There is a plan to do the upgrade?

**Comment by Quietghost** [comment]
Hi Brocy, so far we only had one user who had this issue on a MAC but when he changed to Windows PC the error went away ... not sure what caused it honestly but we are looking into it

**Comment by Brocy** [comment]
Thanks for replaying, we end up making the upgrade if you guys want I can submit a pull request.

**Comment by cedricmoullet** [comment]
Would be great ! Thanks in advance !

**Comment by Quietghost** [comment]
Thanks for the PR, we will check it as soon as possible

**Comment by gillerr** [comment]
fixed with 1.0.2

**Comment by JefredAllan** [comment]
![image](https://user-images.githubusercontent.com/50965394/100770805-95e8d400-33f5-11eb-93b0-7afecd34ba47.png)
looks like this issue still exists. Anyone experiencing the same problem? I'm using Azure AD.
